### ISSUE TITLE
capstone 03 - Take the next step!

### ISSUE THREAD

**Issue by mdewey** [Hectorscreativeworld/assignments#33]
# Take the next step!

With the wireframes, HTML and CSS created, next up and will be to continue on breathing life into our projects. After the CSS, HTML, and wireframes, we need to start thinking about breathing life into our apps. Take today to start creating your front end, ERD and API definitions.

## Objectives

- Start making your front end dynamic and creating components
- Create an ERD for your database, at least a first draft
- Start thinking about your API

## Explorer Mode

- A React with your HTML and CSS
- a ERD Diagram on paper/whiteboard/image/online builder
- A read me with your API endpoints Defined

**Comment by Hectorscreativeworld** [comment]
capstone:
https://github.com/Hectorscreativeworld/the-safe-sitter.git

inventory cont:
https://github.com/Hectorscreativeworld/SweetTartTart.git

ERD: I thought I got it but I still need more help to understand what actually goes into it. 
![Hectors_Capstone_ERD](https://user-images.githubusercontent.com/48931580/60093682-13e08000-9718-11e9-96fc-a8e45edac152.jpg)

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--978506c32fc72f81eabd7234e584cda7e38900af/giphy-6.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/71)**__
